# Site settings
title: Your awesome title
email: claytron.g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey man, I changed all of this text from CodeAnywhere.com.
  P.S. This isn't an endorsement...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ClaytronGreen
github_username:  ClaytronG

# Build settings
markdown: kramdown
